[tool.poetry]
name = "exercise-git"
version = "0.1.0"
description = ""
authors = ["[Bubu] <[bubuy2012@gmail.coml]>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
